name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and tag Docker image
        run: |
          docker build -t bugsiren/webapp:latest -t bugsiren/webapp:$GITHUB_SHA .
          docker images

      - name: Push Docker image
        run: |
          docker push bugsiren/webapp:latest
          docker push bugsiren/webapp:$GITHUB_SHA

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull bugsiren/webapp:latest
            docker stop webapp || true
            docker rm webapp || true
            docker run -d --name webapp -p 5000:5000 bugsiren/webapp:latest
